version: '1'
services:
  mongo:
        ports:
            - '27017:27017'
        container_name: mongodb
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=mongo
        image: mongo

  
  backend-healthcare:
    container_name: backend-healthcare
    build: 
      context: ./backend-healthcare
      dockerfile: Dockerfile
    volumes:
      - ./backend-healthcare:/app
    links:
      - mongo
    ports:
      - "4000:4000"

  ui-healthcare:
    container_name: ui-healthcare
    build:
      context: ./ui-health-care
      dockerfile: Dockerfile
    volumes:
      - ./ui-health-care/src:/app/src
    links:
     - backend-healthcare
    ports:
      - 3000:3000
    
  