version: '1'
services:
  mongo:
        ports:
            - '27017:27017'
        container_name: mongodb
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=mongo
        image: mongo

  mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=mongo
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=mongo
            - ME_CONFIG_BASICAUTH_USERNAME=mongo
            - ME_CONFIG_BASICAUTH_PASSWORD=mongo
        depends_on:
            - mongo
        ports:
          - "8182:8081"

  
  backend-healthcare:
    container_name: backend-healthcare
    build: 
      context: ./backend-healthcare
      dockerfile: Dockerfile
    volumes:
      - ./backend-healthcare:/app
    links:
      - mongo
    ports:
      - "4000:4000"

  ui-healthcare:
    container_name: ui-healthcare
    build:
      context: ./ui-health-care
      dockerfile: Dockerfile
    volumes:
      - ./ui-health-care/src:/app/src
    links:
     - backend-healthcare
    ports:
      - 3000:3000
    
  